const $=id=>document.getElementById(id);const canvas=$('canvas'),ctx=canvas.getContext('2d',{willReadFrequently:true});let original=null,img=new Image();
const sliders=['brightness','smooth','saturation','contrast','sharpen'];
$('pickBtn').onclick=()=>$('fileInput').click();
$('fileInput').onchange=e=>{const f=e.target.files[0];if(!f)return;const url=URL.createObjectURL(f);img.onload=()=>{const max=1800;let w=img.width,h=img.height;if(w>max||h>max){const r=Math.min(max/w,max/h);w=Math.round(w*r);h=Math.round(h*r)}canvas.width=w;canvas.height=h;ctx.drawImage(img,0,0,w,h);original=ctx.getImageData(0,0,w,h);canvas.style.display='block';$('hint').style.display='none';apply();URL.revokeObjectURL(url)};img.src=url};
sliders.forEach(id=>$(id).oninput=apply);
$('resetBtn').onclick=()=>{sliders.forEach(id=>$(id).value=0);apply()};
$('autoBtn').onclick=()=>{$('brightness').value=14;$('smooth').value=3;$('saturation').value=18;$('contrast').value=10;$('sharpen').value=2;apply()};
$('saveBtn').onclick=()=>{if(!original)return alert('Anh hãy chọn ảnh trước.');const a=document.createElement('a');a.href=canvas.toDataURL('image/jpeg',0.95);a.download='photopro-ai.jpg';a.click()};
function apply(){updateLabels();if(!original)return;let data=new Uint8ClampedArray(original.data);const b=+$('brightness').value,c=+$('contrast').value,s=+$('saturation').value,sm=+$('smooth').value,sh=+$('sharpen').value;for(let i=0;i<data.length;i+=4){let r=data[i],g=data[i+1],bl=data[i+2];r=contrast(r+b,c);g=contrast(g+b,c);bl=contrast(bl+b,c);let gray=.299*r+.587*g+.114*bl;data[i]=clamp(gray+(r-gray)*(1+s/100));data[i+1]=clamp(gray+(g-gray)*(1+s/100));data[i+2]=clamp(gray+(bl-gray)*(1+s/100))}let out=new ImageData(data,canvas.width,canvas.height);if(sm>0)out=boxBlur(out,sm);if(sh>0)out=sharpen(out,sh);ctx.putImageData(out,0,0)}
function updateLabels(){brightVal.textContent=brightness.value;smoothVal.textContent=smooth.value;satVal.textContent=saturation.value;contrastVal.textContent=contrast.value;sharpVal.textContent=sharpen.value}
function clamp(v){return Math.max(0,Math.min(255,v))}function contrast(v,c){let f=(259*(c+255))/(255*(259-c));return clamp(f*(v-128)+128)}
function boxBlur(imgd,r){const w=imgd.width,h=imgd.height,src=imgd.data,dst=new Uint8ClampedArray(src);const rad=Math.max(1,Math.min(8,r));for(let y=0;y<h;y++)for(let x=0;x<w;x++){let rr=0,gg=0,bb=0,n=0;for(let dy=-rad;dy<=rad;dy+=rad)for(let dx=-rad;dx<=rad;dx+=rad){let xx=Math.max(0,Math.min(w-1,x+dx)),yy=Math.max(0,Math.min(h-1,y+dy)),p=(yy*w+xx)*4;rr+=src[p];gg+=src[p+1];bb+=src[p+2];n++}let p=(y*w+x)*4;dst[p]=rr/n;dst[p+1]=gg/n;dst[p+2]=bb/n}return new ImageData(dst,w,h)}
function sharpen(imgd,a){const w=imgd.width,h=imgd.height,src=imgd.data,dst=new Uint8ClampedArray(src),k=a*.22;for(let y=1;y<h-1;y++)for(let x=1;x<w-1;x++){let p=(y*w+x)*4;for(let ch=0;ch<3;ch++){let val=src[p+ch]*(1+4*k)-src[p-4+ch]*k-src[p+4+ch]*k-src[p-w*4+ch]*k-src[p+w*4+ch]*k;dst[p+ch]=clamp(val)}}return new ImageData(dst,w,h)}
if('serviceWorker' in navigator){navigator.serviceWorker.register('sw.js').catch(()=>{})}
